### ISSUE TITLE
Github doesn't have a simple "discussion" function

### ISSUE THREAD

**Issue by jimsalterjrs** [jimsalterjrs/perlpv#5]
Hey @Freaky , let's move the kaffeklatsch from that one completed PR into here, so we can stop unticking the "isopen" filter when we want to talk about what we're doing next. :)

**Comment by Freaky** [comment]
There's literally a "Discussions" feature you can turn on over in repository Settings :)

**Comment by jimsalterjrs** [comment]
well why the absolute hell ain't that ON by default... thanks again!
